name: Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm ci

      - run: npm run lint

  size:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: npm install
        run: npm ci

      - name: Size limit
        run: npm run size

  tests-unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: npm install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Unit tests
        run: npm run test

  tests-visual:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: npm install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Visual tests
        run: npm run test:visual
